### ISSUE TITLE
Missing uv-attributes from the FBX export ?

### ISSUE THREAD

**Issue by Samsy** [googlevr/tilt-brush-toolkit#17]
Hello there !
Some brushes need more than 2 component of some UV channels ( like the electricity one's )
Is there any way to deal with that without going by the JSON export ? 
Found out FBX dont export more than 2 component of UV per channel.

**Comment by dubois** [comment]
Hi, Samsy. Sorry for the delay; I didn't see this question earlier.

To answer your question:
> Is there any way to deal with that without going by the JSON export ?

The normal process for using the toolkit is:
1. Import the toolkit .unitypackage into your project
1. Export a .fbx from Tilt Brush
1. Drop the .fbx into your project's Assets/ folder. (The .png files are not needed)

You're correct that FBX only allows 2-component TEXCOORDs, and also that our shaders require 3- and 4-component TEXCOORDs, but you don't need to worry about that. Part of the reason the Toolkit exists is to work around limitations of the .fbx file format.

If you're interested in the details of how we implement that workaround, see TiltBrushToolkit.ModelImportSettings.CollapseUvs() . But again, you don't need to know any of this in order to use the toolkit.

**Comment by dubois** [comment]
Closing -- but if you are still having troubles getting the toolkit to work, please reopen and give details.

**Comment by mahe373662858** [comment]
Hi, Dubois .May I ask you a question.
Using code to dynamically load FBX exported by Tilt Brush in Unity.
FBX can be loaded into a project project project, but tilt brush sdk's code will report errors (single configuration error and Null Reference Exception: Object reference not set to an instance of an object), and the material will not be modified，It's a white model.

**Comment by dubois** [comment]
Hi, @mahe373662858. Please use the issue https://github.com/googlevr/tilt-brush-toolkit/issues/35 that you opened.
