### ISSUE TITLE
Modifying exported fbx and importing to Unity 

### ISSUE THREAD

**Issue by msclecram** [googlevr/tilt-brush-toolkit#31]
Hello,

I'm trying to add rigging and animation (and import them to Unity) to meshes created with TiltBrush. 

When I export a fbx from TiltBrush and import it to Unity everything works fine.  The problem is when I import and export in 3DS Max, all the material are lost inside of Unity. How are the materials stored in the FBX? Is there a 3D CG program (Blender, Maya, etc) that keeps the material linking for Unity?

Also I'm wondering if I'll have to modify the brushes vertex shaders to support skinned animation.

Thanks!

**Comment by dubois** [comment]
Hi, Marcel. The material assignment is governed by Assets/TiltBrush/Scripts/Editor/FbxUtils.cs and ModelImportSettings.cs.

When a 3rd-party program saves the .fbx file, it can remove or overwrite the fbx metadata that the toolkit uses in order to recognize Tilt Brush-created fbx files. You can probably work around this by modifying FbxUtils.GetTiltBrushFbxInfo and adding some other way of detecting Tilt Brush files. For example, always put your Tilt Brush .fbx files in a directory called "Tilt Brush", and do something like:

    if (path.Replace("\\", "/").Contains("/Tilt Brush/") {
        return new FbxInfo {
            isFbx=true,
            tiltBrushVersion=Version.Parse("18.0"),
            requiredToolkitVersion=Version.Parse("1.0")
        };
     }

The material lookup itself happens in ModelImportSettings.OnAssignMaterialModel() which is called by Unity. If the fbx comes from Tilt Brush, and if the material name looks like a Tilt Brush material (see GetDescriptorForStroke()), then we replace the material. Most likely this isn't what's failing in your case.

Some of the brushes use a lot of TEXCOORD data, so you'll also need to make sure that your DCC tool isn't removing, or overwriting any of that data.

Additionally, some of that TEXCOORD data is actually position-like, vector-like, or normal-like. If vertices are getting their positions changed (eg, they're getting split or batched or having transforms baked into them) then it can also require changes to data hidden in texcoords. Probably that isn't affecting you either.

**Comment by dubois** [comment]
> Also I'm wondering if I'll have to modify the brushes vertex shaders

It might depend on the brush. Many of the brushes use surface shaders, so you might be good there. Others use raw vert/frag shaders (for example: particle systems) so you will almost certainly need to skin those.

**Comment by msclecram** [comment]
Hi Paul,
All materials are now linked correctly modifying a bit ModelImportSettings.cs, however it seems some vertex/uv information are lost in the re-importing because some brushes are not working. For example, electricity brush is very chaotic. I tried 3ds Max and blender and more brushes are working correctly with blender.
I'll try the animation first with the working brushes and I'll notify if the skinning is working.

Thanks!

**Comment by dubois** [comment]
The electricity brush is one of those I talked about that has some extra texcoord data in it. Specifically, TEXCOORD1 (aka uv set 2) is an offset from the vertex to the midpoint of the stroke. When skinning, you'll want to skin that as well. Use w=0 so it gets treated as a vector rather than a position. Unlike normals/tangents/bivectors you don't want to skin it with the inverse-transpose; just multiply against your skinning matrix.

It should be possible to convince your DCC tool not to destroy texcoord1. Let me know how you get on!

**Comment by dubois** [comment]
Closing -- but if you are still having troubles getting the this to work, please reopen and give details.
