### ISSUE TITLE
'AssetImporters' does not exist

### ISSUE THREAD

**Issue by Naomi-A-Virtual** [googlevr/tilt-brush-toolkit#37]
Hello,

I've been using Unity 2019.2.0f1 for one of my VR projects. Since recently I downloaded the TiltBrush SDK, I've been having compiler errors and none of the builds would go through (but it plays perfectly in the editor). Here are some examples of the error in the console window:

_Assets\TiltBrush\Scripts\Editor\Glb1Importer.cs(23,32): error CS0234: The type or namespace name 'AssetImporters' does not exist in the namespace 'UnityEditor.Experimental' (are you missing an assembly reference?)
Assets\TiltBrush\Scripts\Editor\Glb1Importer.cs(28,29): error CS0246: The type or namespace name 'ScriptedImporter' could not be found (are you missing a using directive or an assembly reference?)
Assets\TiltBrush\Scripts\Editor\GammaSettings.cs(22,30): error CS0246: The type or namespace name 'EditorWindow' could not be found (are you missing a using directive or an assembly reference?)_

Was the 'AssetImporters' taken out of this version of 'Experimental'? Or did I save something under the wrong directory?

Would really appreciate help from you.

Best,
Naomi

p.s. Here is a section of the error code in Glb1Importer.cs

> using Object = UnityEngine.Object;
> #if UNITY_2017_1_OR_NEWER
> using System;
> using System.IO;
>  
> using UnityEngine;
> using UnityEditor;
> using UnityEditor.Experimental.AssetImporters;

**Comment by n1ckfg** [comment]
I've been encountering an identical error with the Alembic importer (the old UTJ version). Something's up with UnityEditor.Experimental.AssetImporters.

**Comment by dubois** [comment]
Hi, Naomi-Arup. Tilt Brush Toolkit v21 targets the 2018.4 LTS Unity
release. We (I) haven't attempted a port to later versions of the Unity
editor. Probably the issue is shallow and those classes have simply
graduated out of UnityEditor.Experimental in Unity 2019.

>
I'll take a look today.

**Comment by dubois** [comment]
Oh, alternatively, if you are using .fbx only and don't need .glb1 support,
try using the previous release which doesn't rely on AssetImporters.

**Comment by dubois** [comment]
Looked into this a bit.

2019.2 still contains the namespace `UnityEditor.Experimental.AssetImporters`, and it *definitely* still contains the class `UnityEditor.EditorWindow`. Also, I can't repro this with Unity 2019.2.1f1. I expect this is some Unity issue, although since those classes are not (as far as I know) split out into their own packages, I don't know if fiddling with the package manager will help.

I wasn't able to reproduce the issue with 2019.2.1f1. Here is what I did:

- Make a fresh clone of googlevr/tilt-brush-toolkit
- Open it in 2019.2.1f1 and let the upgrade take place
- Fix ugui build failure by explicitly adding Physics2D in the package manager

And here are the dependencies I ended up with for the Tilt Brush Toolkit in 2019.2:

```
{
  "dependencies": {
    "com.unity.ext.nunit": "1.0.0",
    "com.unity.package-manager-ui": "2.2.0",
    "com.unity.test-framework": "1.0.18",
    "com.unity.ugui": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.ui": "1.0.0"
  }
}
```

A couple things I don't understand in your original post:

> none of the builds would go through

What kind of builds do you mean? Standalone builds? Standalone builds will ignore code in Editor/ directories (except maybe if you're using .asmdef files?) so you must have meant something different.

> but it plays perfectly in the editor

Does this mean that your project runs when you hit "Play"? Even in 2019.2, all compiler errors need to be fixed before it will enter play mode.

I think you may be saying:
- You get no compile errors in editor
- You get no compile errors when entering playmode
- You only see compile errors when building standalone

In this case, we need to figure out why your standalone build is including code in Editor/ directories, which probably has to do with .asmdef files. [...]

OK, I think the issue is that `Assets/TiltBrush/Scripts/Editor/TiltBrushToolkitEditor.asmdef` should say `    "autoReferenced": false,` instead of `    "autoReferenced": true,`

Can you try that?

**Comment by dubois** [comment]
Never mind -- I found the issue. I'll push a fix soon; thanks for the report!

**Comment by Naomi-A-Virtual** [comment]
Hi Paul,

Thank you so much for the help. You’re a boss!

Cheers,
Naomi
